insert into user(username,password) values ('user1','a12345678');
insert into user(username,password) values ('user2','a12345678');
insert into user(username,password) values ('user3','a12345678');
insert into user(username,password) values ('user4','a12345678');
insert into user(username,password) values ('user5','a12345678');
insert into user(username,password) values ('user6','a12345678');
insert into user(username,password) values ('user7','a12345678');
insert into user(username,password) values ('user8','a12345678');
select * from user;
insert into record(userid,picurl,record,`time`) values (1,'../upload/01.png','123',now());
insert into record(userid,picurl,record,`time`) values (2,'../upload/02.png','124',now());
insert into record(userid,picurl,record,`time`) values (3,'../upload/03.png','125',now());
insert into record(userid,picurl,record,`time`) values (4,'../upload/04.png','126',now());
insert into record(userid,picurl,record,`time`) values (5,'../upload/05.png','127',now());
insert into record(userid,picurl,record,`time`) values (6,'../upload/06.png','128',now());
insert into record(userid,picurl,record,`time`) values (7,'../upload/07.png','129',now());
insert into record(userid,picurl,record,`time`) values (8,'../upload/08.png','130',now());
select * from record;
insert into share(userid,picurl,message) values (1,'../upload/01.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (2,'../upload/02.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (3,'../upload/03.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (4,'../upload/04.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (5,'../upload/05.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (6,'../upload/06.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (7,'../upload/07.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
insert into share(userid,picurl,message) values (8,'../upload/08.png','“我刚刚在<a href="http://192.168.1.101/dazidenglu.html" style="text-decoration:none;">http://dazidenglu.html</a>练习了打字，速度又变快了，快来和我比赛吧！”');
select * from share;
